---
version: "3"
services:
 devopsdb:
   image: naveen6528/mynewapp:dbimage
   deploy:
    replicas: 3
   ports:
     - "3306:3306"

 application:
   image: naveen6528/mynewapp:appimage
   deploy:
    replicase: 3
   ports:
     - "6528:8080"
   depends_on:
     - "devopsdb"
